const categoryArray = ["Adult Content", "Alcohol/Drugs", "Comedy", "Conspiracy", "Education", "Gambling", "Gaming", "Horror", "LGBT", "Movies/TV", "Music", "News/Politics", "Promotional", "Religion", "Romance", "Sports", "Violence", "Vlog"];
const page = {
    HOME : "https://www.youtube.com/",
    TRENDING : "https://www.youtube.com/feed/trending",
    SUBSCRIPTIONS : "https://www.youtube.com/feed/subscriptions",
    SEARCH : "https://www.youtube.com/results",
    VIDEO : "https://www.youtube.com/watch",
    CHANNEL : "https://www.youtube.com/channel", // FIXME: Multiple urls
    PLAYLIST : "https://www.youtube.com/playlist",
    MIX : "https://www.youtube.com/watch?v=&list="
};

const windowMessages = {
    SendCurator : "SubmitVT",
    FilterHome : "FilterHome"
};

let primaryInner = document.getElementById("primary-inner");

//Checks on initial visit to youtube page
window.onload = function() {
    OnPageChange();
};

//Checks on page change (YouTube does partial loads and can be detected by 'yt-navigate-start' and 'yt-navigate-finish')
window.addEventListener('yt-navigate-finish', OnPageChange);

/**
 * 
 * @param {URL} url 
 */
function getVideoID(url = new URL(window.location.href)) {
    return (new URLSearchParams(url.search)).get('v');
}

// FIXME
function OnPageChange() {
    switch (window.location.href) {
        case (page.HOME):
            window.postMessage(windowMessages.FilterHome, '*');
            break;
        // case (page.TRENDING):
            // FilterTrendingPage();
            // break;
        // case (page.SUBSCRIPTIONS):
            // FilterSubscriptionsPage();
            // break;
        default:
            // TODO: check for parameters not just string match
            if ( (window.location.href).includes(page.VIDEO)) {
                chrome.runtime.sendMessage({greeting: "IsCurator"}, function(response) {
                    if (!document.getElementById("VTCurator") && response.farewell == "true") {
                        createCuratorDiv();
                    }
                });
                chrome.runtime.sendMessage({greeting: "DisableComments"}, function(response) {
                    if (response.farewell == "true") {
                        removeComments();
                    }
                });
                // Filter Recommendations
            }
    }
}

/**
 * Used in curator mode, this function iterates through and creates checkboxes
 * @param {Array<String>} categoryArray 
 */
function addCategories(categoryArray) {
    let innerHTML = "<div id=\"categories\" style=\"column-count:2;\">";
    categoryArray.forEach(element => {
        innerHTML += "<input type=\"checkbox\" id=\"" + element + "\" name=\"filters[]\" value=\"" + element + "\"><label for=\"" + element + "\">" + element + "</label><br>";
    });

    innerHTML += "</div>";
    return innerHTML;
}

/**
 * This behemoth of a function does one simple task, it creates the Curator Div when Curator Mode has been enabled.
 * NOTE: This is only for creating training data for the neural network.
 */
function createCuratorDiv() {
    if (document.getElementById("VTCurator")) {
        return;
    }
    let primaryInner = document.getElementById("primary-inner");
    let curatorDiv = document.createElement("div");
    curatorDiv.setAttribute('id', 'VTCurator');
    curatorDiv.setAttribute('class', 'style-scope ytd-watch-flexy');
    let metaIndex;
    for (let index = 0; index < primaryInner.childNodes.length; index++) {
        if (primaryInner.childNodes[index].id ==="meta") {
            metaIndex = index;
            break;
        }
    }
    primaryInner.insertBefore(curatorDiv, primaryInner.childNodes[metaIndex+1]);

    curatorDiv = document.getElementById("VTCurator");
    // Now we are modifying inside curatorDiv
    let a = document.createElement("ytd-video-secondary-info-renderer");
    a.setAttribute('class', 'style-scope ytd-watch-flexy');
    curatorDiv.appendChild(a);
    // clear autogenerated content
    a.innerHTML = "";

    let VTForm = document.createElement("form");
    VTForm.setAttribute("id", "VTForm");
    VTForm.setAttribute("name", "VTForm");
    VTForm.setAttribute("enctype", "multipart/form-data");
    VTForm.setAttribute("method", "post");
    a.appendChild(VTForm);

    let heading = document.createElement("h2");
    heading.innerHTML = "ValueTube Curator";
    heading.setAttribute('class', 'title style-scope ytd-video-primary-info-renderer');
    heading.setAttribute("style", "padding-bottom:5px;");
    VTForm.appendChild(heading);
    let b = document.createElement("ytd-expander");
    b.setAttribute('class', 'style-scope ytd-video-secondary-info-renderer');
    b.setAttribute('style', '--ytd-expander-collapsed-height:80px;');
    b.setAttribute('collapsed', '""');
    VTForm.appendChild(b);
    let content;
    //Add show more and show less button
    for (let index = 0; index < b.childNodes.length; index++) {
        if (b.childNodes[index].id == "content") {
            content = b.childNodes[index];
        } else if (b.childNodes[index].id == "less") {
            let less = document.createElement("yt-formatted-string");
            less.setAttribute('class', 'less-button style-scope ytd-video-secondary-info-renderer');
            less.setAttribute('slot', 'less-button');
            less.setAttribute('role', 'button');
            b.childNodes[index].appendChild(less);
            less.innerHTML = "Show Less";
        } else if (b.childNodes[index].id == "more") {
            let more = document.createElement("yt-formatted-string");
            more.setAttribute('class', 'less-button style-scope ytd-video-secondary-info-renderer');
            more.setAttribute('slot', 'more-button');
            more.setAttribute('role', 'button');
            b.childNodes[index].appendChild(more);
            more.innerHTML = "Show More";
        }
    }
    let c = document.createElement("div");
    c.setAttribute('id', 'content')
    c.setAttribute('class', 'style-scope ytd-expander');
    content.appendChild(c);
    // d will contain checkboxes
    let d = document.createElement("yt-formatted-string");
    d.setAttribute('class', 'content style-scope ytd-video-secondary-info-renderer');
    d.setAttribute('force-default-style', '""');
    d.setAttribute('split-lines', '""');
    c.appendChild(d);
    d.innerHTML = addCategories(categoryArray);

    //secondary info renderer
    let infoRenderer = document.createElement("div");
    infoRenderer.setAttribute("class", "style-scope ytd-video-secondary-info-renderer");
    VTForm.appendChild(infoRenderer);
    infoRenderer.innerHTML = "";

    
    // Submit button
    let buttonDiv = document.createElement("div");
    buttonDiv.setAttribute("class", "style-scope ytd-video-secondary-info-renderer");
    
    infoRenderer.appendChild(buttonDiv);

    let buttonRenderer = document.createElement("ytd-subscribe-button-renderer");
    buttonRenderer.setAttribute("class", "style-scope ytd-video-secondary-info-renderer");
    buttonRenderer.setAttribute("use-keyboard-focused", "");
    buttonRenderer.setAttribute("style", "display:flow-root; text-align:right;");

    buttonDiv.appendChild(buttonRenderer);
    buttonRenderer.innerHTML = "";

    let paperButton = document.createElement("paper-button");
    paperButton.setAttribute("noink", "");
    paperButton.setAttribute("id", "VTSubmitButton");
    paperButton.setAttribute("class", "style-scope ytd-subscribe-button-renderer");
    paperButton.setAttribute("role", "button");
    paperButton.setAttribute("tabindex", "0");
    paperButton.setAttribute("animated", "");
    paperButton.setAttribute("elevation", "0");
    paperButton.setAttribute("aria-disabled", "false");
    paperButton.setAttribute("style", "background-color: #00a6ff; display: inline-block; margin-right: 40px;");

    paperButton.setAttribute("onclick", "window.postMessage('" + windowMessages.SendCurator + "', '*')");

    buttonRenderer.appendChild(paperButton);

    let formattedString = document.createElement("yt-formatted-string");
    formattedString.setAttribute("class", "style-scope ytd-subscribe-button-renderer")
    formattedString.setAttribute("style", "");
    
    paperButton.appendChild(formattedString);
    formattedString.innerHTML = "Submit";
    
}

function ModifyRecommendationFeed() {
    let videoIDs = [];

	let videos = document.getElementsByTagName('ytd-compact-video-renderer');

	for(index = 0; index < videos.length; index++){

		let link = videos[index].getElementsByTagName("a")[0].getAttribute('href');

		let videoID = getVideoId(new URL(link, "https://www.youtube.com"))

		if(videoID == null){
			continue;
		}
		
		videoIDs.push({"vID": videoID, "value": false});
	}


	return videoIDs;
    
}

function addCategories(categoryArray) {
    let innerHTML = "<div id=\"categories\" style=\"column-count:2;\">";
    categoryArray.forEach(element => {
        innerHTML += "<input type=\"checkbox\" id=\"" + element + "\" name=\"filters[]\" value=\"" + element + "\"><label for=\"" + element + "\">" + element + "</label><br>";
    });

    innerHTML += "</div>";
    return innerHTML;
}

function removeCuratorDiv() {
    primaryInner = document.getElementById("primary-inner");
    for (let index = 0; index < primaryInner.childNodes.length; index++) {
        if (primaryInner.childNodes[index].id === "VTCurator") {
            primaryInner.removeChild(primaryInner.childNodes[index]);
            break;
        }
    }
}

function GetSection() {
    return document.getElementById("contents");
}

function removeComments() {
    const commentSection = document.getElementsByTagName("ytd-comments")[0];

    let observer = new MutationObserver(mutations => {
        for(let mutation of mutations) {
             for(let addedNode of mutation.addedNodes) {
                 if (addedNode.parentElement === commentSection && addedNode.nodeName === "YTD-ITEM-SECTION-RENDERER") {
                    observer.disconnect();
                    addedNode.parentNode.removeChild(addedNode);
                    addCommentMessage(commentSection);
                  }
              }
         }
     });
     observer.observe(commentSection, { childList: true, subtree: true });
}

function addCommentMessage(commentSection) {
    let itemSection = document.createElement("ytd-item-section-renderer");
    itemSection.id = "sections";
    itemSection.setAttribute("initial-count", "2");
    itemSection.class = "style-scope ytd-comments";

    commentSection.appendChild(itemSection);

    itemSection = commentSection.getElementsByTagName("ytd-item-section-renderer")[0];
    for (let index = 0; index < itemSection.childNodes.length; index++) {
        if (itemSection.childNodes[index].id === "contents") {
            contents = itemSection.childNodes[index];
            break;
        }
    }

    messageRenderer = document.createElement("ytd-message-renderer");
    messageRenderer.class = "style-scope ytd-item-section-renderer";
    contents.appendChild(messageRenderer);

    ytdMessageRenderer = contents.childNodes[0];

    spanText = document.createElement("span");
    spanText.dir = "auto";
    spanText.class = "style-scope yt-formatted-string";
    spanText.innerHTML = "Comments are turned off by the ValueTube Extension";

    for (let index = 0; index < ytdMessageRenderer.childNodes.length; index++) {
        if (ytdMessageRenderer.childNodes[index].id === "message") {
            message = ytdMessageRenderer.childNodes[index];
            break;
        }
    }

    message.appendChild(spanText);
    
}

// create an array that allows to pass a string of words. 
// create an array that passess tag (youtube tag "href")
//copied from youtube link search "avengers trailer"

/** 
* @param {url} url
*/
function returnVideo(url){

    let contents = getVideoID();
    let getVideoID = []; 

    let href = document.getElementById('ytd-video-renderer'); 
    videos.forEach(element => {
        let link = element.getElementById("a")[0].getAttribute("href");
        let getVideoID = getVideoID(new URL(link,"http://www.youtube.com"));
        videos.push({getVideoID : false});
        
    });


}

/**
 * This function collects every videos ID from the YouTube Homepage
*/
function GetHomePageVideoIDs() {
    let contents = GetSection();
    let videoIDs = [];
    let videoObjects = [];
    // TODO: Depending on users options remove posts
    // let sections = contents.getElementsByTagName("ytd-rich-section-renderer");
    let videos = contents.getElementsByTagName("ytd-rich-item-renderer");
    for (let index = 0; index < videos.length; index++) {
        let link = videos[index].getElementsByTagName("a")[0].getAttribute("href");
        let videoID =  getVideoID(new URL(link, "https://www.youtube.com"));
        // If first link is a channel ID (e.g. youtube posts)
        if (videoID == null) {
            continue;
        }
        videoIDs.push(videoID);
        videoObjects.push({"vID" : videoID, "element" : videos[index]});
    }
    return {videoIDs, videoObjects};
}

function CreateJForm() {
    let formData = new FormData(document.forms.namedItem("VTForm")); 
    let JForm = {"vID" : getVideoID()};
        
    for (var pair of formData.entries()) {
        if (pair[0].includes("[]")) {
            if (pair[0] in JForm) {
                JForm[pair[0]].push(pair[1]);
            } else {
                JForm[pair[0]] = [pair[1]];
            }
        } else {
            JForm[pair[0]] = pair[1];
        }
    }
    return JForm;
}

window.addEventListener("message", function(event) {
    if (event.source != window)
        return

    if (event.data) {
        switch (event.data) {
            // TODO: Add user feedback to button
            case windowMessages.SendCurator:
                let JForm = CreateJForm();
                chrome.runtime.sendMessage({greeting : windowMessages.SendCurator, data : JForm}, function (response) {
                    if (response.farewell == false) {
                        console.error("An Error occured trying to add your curated filters.");
                    } else if (response.farewell == true) {
                        console.log("Success! Curated Filters added.");
                    }
                });
                break;
            case windowMessages.FilterHome:
                let homePageInfo = GetHomePageVideoIDs();
                chrome.runtime.sendMessage({greeting : windowMessages.FilterHome, data : homePageInfo["videoIDs"]}, function (response) {
                    if (!response.farewell) {
                        console.error("An Error occured trying to filter the home page");
                    } else if (response.farewell) {
                        console.log("Success! Home page filtered!");
                        console.log("Extension Response: ");
                        console.log(response.data);
                        // TODO: Use APIResponse Data
                        // RemoveVideoElements(homePageInfo[1], response.farewell.data);
                    }
                });
                break;
            default:
                console.error("Error: Unknown message");
                break;
        }
    }
        // TODO: Error Handling   
})
