let categoryArray = ["Alcohol", "Conspiracy", "Drugs", "Educational", "Gambling", "Gaming", "Horror", "LGBT", "Memes", "Politics", "Relationships", "Religion", "Self-harm", "Sports", "Suggestive content", "Thrill Seeking", "Violence", "Weaponry", "News", "Music"];
let primaryInner = document.getElementById("primary-inner");

function createCuratorDiv() {
    let primaryInner = document.getElementById("primary-inner");
    let curatorDiv = document.createElement("div");
    curatorDiv.setAttribute('id', 'VTCurator');
    curatorDiv.setAttribute('class', 'style-scope ytd-watch-flexy');
    let metaIndex;
    for (let index = 0; index < primaryInner.childNodes.length; index++) {
        if (primaryInner.childNodes[index].id ==="meta") {
            metaIndex = index;
            break;
        }
    }
    primaryInner.insertBefore(curatorDiv, primaryInner.childNodes[metaIndex+1]);

    curatorDiv = document.getElementById("VTCurator");
    // Now we are modifying inside curatorDiv
    let a = document.createElement("ytd-video-secondary-info-renderer");
    a.setAttribute('class', 'style-scope ytd-watch-flexy');
    curatorDiv.appendChild(a);
    // clear autogenerated content
    a.innerHTML = "";

    let heading = document.createElement("h2");
    heading.innerHTML = "ValueTube Curator";
    heading.setAttribute('class', 'title style-scope ytd-video-primary-info-renderer');
    a.appendChild(heading);
    let b = document.createElement("ytd-expander");
    b.setAttribute('class', 'style-scope ytd-video-secondary-info-renderer');
    b.setAttribute('style', '--ytd-expander-collapsed-height:80px;');
    b.setAttribute('collapsed', '""');
    a.appendChild(b);
    // clear autogenerated content
    b.innerHTML = "";
    let c = document.createElement("div");
    c.setAttribute('id', 'content')
    c.setAttribute('class', 'style-scope ytd-expander');
    b.appendChild(c);
    // d will contain checkboxes
    let d = document.createElement("yt-formatted-string");
    d.setAttribute('class', 'content style-scope ytd-video-secondary-info-renderer');
    d.setAttribute('force-default-style', '""');
    d.setAttribute('split-lines', '""');
    c.appendChild(d);
    // Iterate through category array and create checkboxes and append them to d
    d.innerHTML = '<span dir="auto" class="style-scope yt-formatted-string">If you want more MEME REVIEW click HERE: </span>';
}


function removeCuratorDiv() {
    for (let index = 0; index < primaryInner.childNodes.length; index++) {
        if (element.id ==="VTCurator") {
            primaryInner.removeChild(primaryInner.childNodes[index]);
        }
    }
}

/* HTML LAYOUT
<div id="VTCurator" class="style-scope ytd-watch-flexy">
    <ytd-video-secondary-info-renderer class="style-scope ytd-watch-flexy">
        <h2 class="title style-scope ytd-video-primary-info-renderer">ValueTube Curator</h2>
        <ytd-expander class="style-scope ytd-video-secondary-info-renderer" style="--ytd-expander-collapsed-height:80px;" collapsed="">
            <!--css-build:shady-->
            <div id="content" class="style-scope ytd-expander">
                <yt-formatted-string class="content style-scope ytd-video-secondary-info-renderer" force-default-style="" split-lines="">
                    <span dir="auto" class="style-scope yt-formatted-string">If you want more MEME REVIEW click HERE: </span>
                </yt-formatted-string>
            </div>
        
            <paper-button id="less" aria-expanded="true" noink="" class="style-scope ytd-expander" hidden="" role="button" tabindex="0" animated="" elevation="0" aria-disabled="false">
            <!--css-build:shady-->
            </paper-button>
            <paper-button id="more" aria-expanded="false" noink="" class="style-scope ytd-expander" role="button" tabindex="0" animated="" elevation="0" aria-disabled="false" hidden="">
            <!--css-build:shady-->
            </paper-button>
        </ytd-expander>
    </ytd-video-secondary-info-renderer>
</div>
*/